# Model-specific configurations
logistic_regression:
  C: 0.1
  class_weight: balanced
  max_iter: 1000
  solver: liblinear

gradient_boosting:
  n_estimators: 200
  learning_rate: 0.05
  max_depth: 4
  subsample: 0.8
  random_state: 42

random_forest:
  n_estimators: 200
  max_depth: 10
  min_samples_split: 10
  min_samples_leaf: 4
  random_state: 42

xgboost:
  n_estimators: 200
  learning_rate: 0.1
  max_depth: 3
  subsample: 0.8
  colsample_bytree: 0.8
  random_state: 42

evaluation:
  metrics:
    - auc
    - precision
    - recall
    - f1
  cv_folds: 5